### ISSUE TITLE
Improve autoloader to not load columns automatically from dir

### ISSUE THREAD

**Issue by DGStefan** [codepress/admin-columns#274]
HS #15275

---
I have the plugin used for various clients that are hosted on WPEngine and Pantheon, both of which use multiple deployment/build processes. I've had issues on both hosting as usually the deployment process will only overwrite/add files but not remove any files if the whole website is not a directory. This will obviously be an issue if a user/dev uses FTP or other methods to update the plugin via overwriting. In this day in age, I don't think this is very acceptable, as the ONLY way the plugin can be updated successfully would be to either 1. use the wordpress plugins page 2. Update via FTP by removing the folder first and uploading, which not everyone will do 3. have a repository of the whole site which is also uncommon, and wp-content/plugins is usually ignored anyways.

Due to how your autoloader works, it seems to pick up files in the classes folder even if it is not being used. For a specific example, the latest free plugin has broken some clients' installs as classes/Columns/Post/Roles.php, Parents.php,and classes/Columns/Media/Parent.php were still present.

**Comment by davidmosterd** [comment]
I think we can make this work. Based on Composer, I made a small autoloader classmap script. I am working out wether to do it with a fallback to PSR-4 search/find. Either way, we can use this for the columns. Only thing is that adding files requires some form calling a script and we can't forget this when shipping.

**Comment by davidmosterd** [comment]
Solution is presented, the new build-tool will generate the required classmaps, but it falls back.

As the file-loader is deprecated for production; I suggest we think about removing the Underscore legacy to keep it all clean.
