### ISSUE TITLE
TypeError: this.container is null

### ISSUE THREAD

**Issue by michealjroberts** [codepress/admin-columns#287]
Seems that on updating to Wordpress 5.4.3 the plugin throws the following error within scripts:

```
TypeError: this.container is null
```

It occurs on most admin pages where there is a post or custom-post listing.

The line in question that is causing this break is line **1545** of _assets/js/table.js_.

`this.buttons = this.container.querySelector('.ac-table-actions-buttons'),`

**Comment by DGStefan** [comment]
@michealjroberts 
Please provide more information about this bug.
On which page do you have this error?
Is there a file reference or line / char position where the error occurs?
We'll need more information and I also suspect it is not a WordPress 5.4.3 issue.

**Comment by michealjroberts** [comment]
Hi Stefan, apologies, this is on any page where the use of admin-columns is a part of - so, post pages, and any custom-post pages in the admin section.

**Comment by michealjroberts** [comment]
Disbaling admin-columns stops the bug occuring.

**Comment by michealjroberts** [comment]
Happens on this line: `this.buttons = this.container.querySelector('.ac-table-actions-buttons'),`

**Comment by michealjroberts** [comment]
Line 1545 of `assets/js/table.js.`

**Comment by michealjroberts** [comment]
@DGStefan Please see my updated comment.

**Comment by michealjroberts** [comment]
Is there any update on this bug at all?

**Comment by DGStefan** [comment]
We were not able to reproduce the issue but made a fix after all that should prevent this from happening. It is already released in the pro version and the free version will released any time soon

**Comment by michealjroberts** [comment]
Thanks Stefan - will feedback when I have made the update.
