### ISSUE TITLE
Customization Help

### ISSUE THREAD

**Issue by tazcrzy** [codepress/admin-columns#294]
Trying to add a custom column which would display both text and currency information.  I have created a new column, per the template, however when I go to use the custom column, I immediately get this error: _**The column could not be loaded because of an unknown error**_ and can do nothing else.  I can find no assistance on resolving this error.  Can anyone help?  Thank you.

**Comment by DGStefan** [comment]
@tazcrzy Sorry, for the extremely late response.
You can ask this kind of question directly to our email support, forum or chat on our website.
If you still have some issues, let us know through one of those channels. I will close this topic here.
