### ISSUE TITLE
Plugin causes error

### ISSUE THREAD

**Issue by asha23** [codepress/admin-columns#346]
Getting an issue where the latest version of the plugin throws the following error:

Server is running PHP 7.4.21
Using the lite version of the plugin. Version 4.4.5

```
An error of type E_ERROR was caused in line 73 of the file
 /var/www/*****/wp-content/plugins/codepress-admin-columns/classes/AdminColumns.php.
 Error message: Uncaught Error: Class 'AC\Admin\Notice\ReadOnly' not found
 in
 /var/www/*****/wp-content/plugins/codepress-admin-columns/classes/AdminColumns.php:73
```

I'm not seeing this error when I test locally, oddly. Just wondered if you might know what might be causing it.  Thanks

**Comment by asha23** [comment]
Closed as posted in the wrong place - sorry

**Comment by DGStefan** [comment]
@asha23 I suspecting this is a caching error.
The ReadOnly class is renamed to ReadOnlyListscreen and the call in AdminColumn is correct in the master branch.
Maybe reinstalling the plugin will fix the issue?

**Comment by asha23** [comment]
I will try that. Thanks.
